services:
  - type: web
    name: descargador-videos
    runtime: docker
    plan: free
    autoDeploy: true
    branch: main
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production